### ISSUE TITLE
wheel to turn x slides to the right or left on page load automatically. Please Advise.

### ISSUE THREAD

**Issue by mercuryyy** [lijingcheng/JCWheelView#1]
Hey first of all great great resource! i managed to customize it to what i needed.

How can i set the wheel to turn x slides to the right or left on page load automatically as if they were moved by the user (so the colors in the middle change as its moving as if the user is moving it).

Thanks again for your hard work here.

**Comment by lijingcheng** [comment]
@mercuryyy now, you can use the selectedIndex property in JCWheelView...
